config/routes.rb
Bloccit::Application.routes.draw do
  get "comments/new"
  devise_for :users
  resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post 'down-vote' => 'votes#down_vote', as: :down_vote

  end


  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  default_scope { order('created_at DESC') }

  validates :user, presence: true
  validates :body, length: { minimum: 5 }, presence: true

  after_create :send_favorite_emails

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      if should_recieve_update_for?(favorite)
        FavoriteMailer.new_comment(favorite.user, post, self).deliver
      end
    end
  end

  def should_recieve_update_for?(favorite)
    (user_id != favorite.user_id) && favorite.user.email_favorites?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :js

  def create
    @post = Post.find(params[:post_id])
    @comments = @post.comments

    @comment = current_user.comments.build( comment_params )
    @comment.post = @post

    authorize @comment

    if @comment.save
      flash[:notice] = "Comment was saved."
    elsif @comment.errors.any?
      flash[:error] = "Error#{'s' if @comment.errors.count > 1} saving comment: 
      #{@comment.errors.full_messages.join(', ')}"
    else
      flash[:error] = "There was an error saving the comment. Please try again."
    end

    respond_with(@comment) do |format|
      format.html { redirect_to [@post.topic, @post] }
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @topic = @post.topic
    @comment = Comment.find(params[:id])
    body = @comment.body

    authorize @comment
    if @comment.destroy
      flash[:notice] = "Comment was deleted successfully."
    else
      flash[:error] = "There was an error deleting the post. Please try again."
    end

    respond_with(@comment) do |format|
      format.html { redirect_to [@post.topic, @post] }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= content_tag :div, class: 'media', id: "comment-#{comment.id}" do %>
  <% if comment.user.avatar? %>
    <div class="pull-left" href="#">
      <%= image_tag(comment.user.avatar.small.url) %>
    </div>
  <% end %>
  <div class="media-body">
    <%= comment.body %>
    <small>
      <p>
        submitted <%= time_ago_in_words(comment.created_at) %> ago by 
        <%= comment.user.name %>
        <% if policy(comment).destroy? %>
          | <%= link_to "Delete", [comment.post, comment], method: :delete, remote: true, data: { confirm: 'Are you sure you want to delete this comment?'} %>
        <% end %>
      </p>
    </small>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(:comment, as: post, url: post_comments_path(post), action: "create", remote: true) do |f| %>
  <div class="form-group">
    <%= f.text_field :body, rows: 8, class: 'form-control', placeholder: "Enter comment" %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.valid? %>
  $("<%= escape_javascript(render(@comment)) %>").hide().prependTo(".js-comments").fadeIn();
  $('#comment_body').val('');
<% else %>
  $('#comment_body').val('');
<% end %>  

app/views/comments/destroy.js.erb
<% if @comment.destroyed? %>
  $('#comment-' +<%= @comment.id %>).fadeOut();
  $('.js-comments-count').html("<%= @comment.user.comments.count %> comments")
<% else %>
  $('#comment-' +<%= @comment.id %>).prepend("<div class='alert alert-danger' role='alert'>
    <button type='button' class='close' data-dismiss='alert'>&times;</button>
    <%= flash[:eror] %></div>");
<% end %>